# Generated by Django 2.1.1 on 2018-09-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Motors',
        ),
    ]
